### ISSUE TITLE
Qumulo upgrade failed

### ISSUE THREAD

**Issue by kharam1436** [Qumulo/power-tools#7]
We've tried to upgrade qumulo with Jenkins and python script. Unfortunately, the upgrade failed. The error message is timeout error. The below is the failure message that I got.

One thing that I feel interested is that we've upgrade two qumulo host successfully, and we've failed on two hosts.
**Success**
2.1.5 -> 3.1.2 (chagas-fs)
2.1.5 -> 3.1.2 (dengue-fs)

**failed**
2.1.5 -> 3.1.2 (ebola-fs)
3.0.2 -> 3.1.2 (gout-fs)

ebola-fs (2.1.5.1 -> 3.1.2)
```
+ docker run --rm -e QUMULO_HOST=10.158.103.146 -e QUSER=**** -e QPASS=**** -e VERSION=3.1.2 -e MODE=upgrade -t qumulo-python
this is upgrade section
2020-06-24 15:02:43 | Logging into Qumulo Cluster [10.158.103.146]
2020-06-24 15:02:43 | Login succesful
2020-06-24 15:02:43 | Upgrading from: 2.14.5.1
2020-06-24 15:02:43 | Upgrading to:   3.1.2
2020-06-24 15:02:44 | The upgrade steps will include:
2020-06-24 15:02:44 |  1:   3.0.0.3  |  qimg: qumulo_upgrade_3.0.0.3.qimg
2020-06-24 15:02:44 |  2:     3.1.0  |  qimg: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:02:44 |  3:     3.1.2  |  qimg: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:02:44 | Error creating directory '/upgrade': Error 409: fs_entry_exists_error: { ino=1000003 }
Backtrace:
    duplicate_create at fs/create.c:189
    create_common_internal at fs/create.c:265
    qfs_mkdir at fs/create.c:377
    run_txn_and_get_file_info_for_audit at fs/audit/run_audit.c:42
    fs_prepare_wrapper at fs/restart.c:47
    general_txn_work_item_prepare at transaction/work_item.c:62
    trans_once at transaction/restart.c:543
    fs_check_restarts at fs/restart.c:128
    do_restart_check at transaction/restart.c:394
    trans_run_restartable_common at transaction/restart.c:622
    trans_run_restartable_work_stack at transaction/restart.c:703
    quorum_user_interlock_run_restartable at cluster/quorum/user.c:824
    real_trans_restart_ops_quorum_user_interlock_run_restartable at transaction/restart.c:133
    trans_run_restartable at transaction/restart.c:745
    fs_run_restartable at fs/restart.c:237
    fs_run_audit at fs/audit/run_audit.c:98
    fs_run_restartable_with_audit at fs/audit/run_audit.c:174
    fs_mkdir at fs/create_directory.c:92
    fs_mkdir at fs/create_directory.c:104
    real_api_fs_mkdir at api/files/fs.c:303
    create_file at api/files/files_impl.c:929
    create_or_rename_directory_entry at api/files/files_impl.c:1121
    v1_files_entries_post at api/files/files_impl.c:1198
    v1_files_entries_post at build/release/api/files/files.c:37750
    v1_files_entries_post_handle_if_matches at build/release/api/files/files.c:38556
    v1_files_post at build/release/api/files/files.c:39331
    rest_request_handler_adapter_post at api/api.c:599
    dispatch_request at api/api.c:921
    uri_dispatch_handle at api/api.c:1004
    common_api_event_dispatcher at api/api.c:1034
    api_event_dispatcher at api/api.c:1159
2020-06-24 15:02:44 | Begin download of qimg(s) to Qumulo cluster
2020-06-24 15:02:44 | Downloading: qumulo_upgrade_3.0.0.3.qimg
2020-06-24 15:02:44 | Starting download of qimg file: qumulo_upgrade_3.0.0.3.qimg
0%  5%  10%  15%  20%  25%  30%  35%  40%  45%  50%  55%  60%  65%  70%  75%  80%  85%  90%  95%  
2020-06-24 15:03:04 | Completed download of qimg file: qumulo_upgrade_3.0.0.3.qimg
2020-06-24 15:03:04 | Load qimg file onto Qumulo Cluster via API: qumulo_upgrade_3.0.0.3.qimg
2020-06-24 15:03:22 | qimg loaded: /upgrade/qumulo_upgrade_3.0.0.3.qimg
2020-06-24 15:03:22 | delete local qimg: qumulo_upgrade_3.0.0.3.qimg
2020-06-24 15:03:22 | Downloading: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:22 | Starting download of qimg file: qumulo_upgrade_3.1.0.qimg
0%  5%  10%  15%  20%  25%  30%  35%  40%  45%  50%  55%  60%  65%  70%  75%  80%  85%  90%  95%  
2020-06-24 15:03:41 | Completed download of qimg file: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:41 | Load qimg file onto Qumulo Cluster via API: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:58 | qimg loaded: /upgrade/qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:59 | delete local qimg: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:59 | Downloading: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:03:59 | Starting download of qimg file: qumulo_upgrade_3.1.2.qimg
0%  5%  10%  15%  20%  25%  30%  35%  40%  45%  50%  55%  60%  65%  70%  75%  80%  85%  90%  95%  
2020-06-24 15:04:24 | Completed download of qimg file: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:04:24 | Load qimg file onto Qumulo Cluster via API: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:04:40 | qimg loaded: /upgrade/qumulo_upgrade_3.1.2.qimg
2020-06-24 15:04:41 | delete local qimg: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:04:41 | Completed download of qimg(s) to Qumulo cluster
2020-06-24 15:04:41 | upgrade to: 3.0.0.3 with qimg: qumulo_upgrade_3.0.0.3.qimg
2020-06-24 15:04:41 | Preparing cluster for upgrade. Cluster will be fully available during this time.
2020-06-24 15:04:42 | Preparing...
2020-06-24 15:04:59 | Preparing...
2020-06-24 15:05:16 | Preparing...
2020-06-24 15:05:34 | Preparing...
2020-06-24 15:05:51 | Upgrade prepared for: /upgrade/qumulo_upgrade_3.0.0.3.qimg - status: UPGRADE_PREPARED
2020-06-24 15:05:51 | Begin upgrade arm process.
2020-06-24 15:06:28 | Qumulo cluster armed with /upgrade/qumulo_upgrade_3.0.0.3.qimg. Reloading Qumulo.
2020-06-24 15:06:38 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.0.0.3.qimg ...
2020-06-24 15:06:59 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.0.0.3.qimg ...
2020-06-24 15:07:19 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.0.0.3.qimg ...
2020-06-24 15:07:39 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.0.0.3.qimg ...
2020-06-24 15:07:59 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.0.0.3.qimg ...
2020-06-24 15:08:19 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.0.0.3.qimg ...
2020-06-24 15:08:39 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.0.0.3.qimg ...
2020-06-24 15:08:39 | Completed upgrade to 3.0.0.3
2020-06-24 15:08:39 | --------------------------------------------------------------------------------
2020-06-24 15:08:39 | upgrade to: 3.1.0 with qimg: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:08:39 | Preparing cluster for upgrade. Cluster will be fully available during this time.
2020-06-24 15:08:39 | Preparing...
2020-06-24 15:08:57 | Preparing...
2020-06-24 15:09:14 | Preparing...
2020-06-24 15:09:31 | Preparing...
2020-06-24 15:09:49 | Upgrade prepared for: /upgrade/qumulo_upgrade_3.1.0.qimg - status: UPGRADE_PREPARED
2020-06-24 15:09:49 | Begin upgrade arm process.
Traceback (most recent call last):
  File "/data/qupgrade.py", line 398, in <module>
    upgrade_cluster()
  File "/data/qupgrade.py", line 394, in upgrade_cluster
    qr.upgrade_cluster(args.vers, api, sharepass=args.sharepass, download_only = args.download_only)
  File "/data/qupgrade.py", line 257, in upgrade_cluster
    self.install_upgrades(api)
  File "/data/qupgrade.py", line 184, in install_upgrades
    api.upgrade_to(d['release'], "%s/%s" % (UPGRADE_PATH, d['qimg']))
  File "/data/qupgrade.py", line 378, in upgrade_to
    self.upgrade_arm(qimg_path)
  File "/data/qupgrade.py", line 333, in upgrade_arm
    resp = self.rc.upgrade.config_put(qimg_path, 'UPGRADE_TARGET_ARM')
  File "/usr/local/lib/python2.7/site-packages/qumulo/rest_client.py", line 81, in wrapper
    self.client.conninfo, self.client.credentials, *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/qumulo/rest/upgrade.py", line 48, in config_put
    return request.rest_request(conninfo, credentials, method, str(uri), body=req)
  File "/usr/local/lib/python2.7/site-packages/qumulo/lib/request.py", line 596, in rest_request
    rest.get_response()
  File "/usr/local/lib/python2.7/site-packages/qumulo/lib/request.py", line 520, in get_response
    self.response = self.conn.getresponse()
  File "/usr/local/lib/python2.7/httplib.py", line 1161, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)
```

Here is another failure `gout-fs 3.0.2 -> 3.1.2`
```
+ docker run --rm -e QUMULO_HOST=10.158.111.247 -e QUSER=**** -e QPASS=**** -e VERSION=3.1.2 -e MODE=upgrade -t qumulo-python
this is upgrade section
2020-06-24 15:02:44 | Logging into Qumulo Cluster [10.158.111.247]
2020-06-24 15:02:44 | Login succesful
2020-06-24 15:02:44 | Upgrading from: 3.0.2
2020-06-24 15:02:44 | Upgrading to:   3.1.2
2020-06-24 15:02:44 | The upgrade steps will include:
2020-06-24 15:02:44 |  1:     3.1.0  |  qimg: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:02:44 |  2:     3.1.2  |  qimg: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:02:44 | Error creating directory '/upgrade': Error 409: fs_entry_exists_error: { ino=398136958 }
Backtrace:
    duplicate_create at fs/create.c:188
    create_common_internal at fs/create.c:264
    qfs_mkdir at fs/create.c:373
    run_txn_and_get_file_info_for_audit at fs/audit/run_audit.c:42
    fs_prepare_wrapper at fs/restart.c:47
    general_txn_work_item_prepare at transaction/work_item.c:62
    trans_once at transaction/restart.c:543
    fs_check_restarts at fs/restart.c:128
    do_restart_check at transaction/restart.c:394
    trans_run_restartable_common at transaction/restart.c:622
    trans_run_restartable_work_stack at transaction/restart.c:703
    quorum_user_interlock_run_restartable at cluster/quorum/user.c:823
    real_trans_restart_ops_quorum_user_interlock_run_restartable at transaction/restart.c:133
    trans_run_restartable at transaction/restart.c:745
    fs_run_restartable at fs/restart.c:237
    fs_run_audit at fs/audit/run_audit.c:98
    fs_run_restartable_with_audit at fs/audit/run_audit.c:174
    fs_mkdir at fs/create_directory.c:82
    fs_mkdir at fs/create_directory.c:94
    real_api_fs_mkdir at api/files/fs.c:304
    create_or_rename_directory_entry at api/files/files_impl.c:1080
    v1_files_entries_post at api/files/files_impl.c:1156
    v1_files_entries_post at build/release/api/files/files.c:36874
    v1_files_entries_post_handle_if_matches at build/release/api/files/files.c:37804
    v1_files_post at build/release/api/files/files.c:38624
    rest_request_handler_adapter_post at api/api.c:599
    dispatch_request at api/api.c:921
    uri_dispatch_handle at api/api.c:1004
    common_api_event_dispatcher at api/api.c:1034
    api_event_dispatcher at api/api.c:1159
2020-06-24 15:02:44 | Begin download of qimg(s) to Qumulo cluster
2020-06-24 15:02:44 | Downloading: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:02:44 | Starting download of qimg file: qumulo_upgrade_3.1.0.qimg
0%  5%  10%  15%  20%  25%  30%  35%  40%  45%  50%  55%  60%  65%  70%  75%  80%  85%  90%  95%  
2020-06-24 15:03:12 | Completed download of qimg file: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:12 | Load qimg file onto Qumulo Cluster via API: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:24 | qimg loaded: /upgrade/qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:24 | delete local qimg: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:03:24 | Downloading: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:03:24 | Starting download of qimg file: qumulo_upgrade_3.1.2.qimg
0%  5%  10%  15%  20%  25%  30%  35%  40%  45%  50%  55%  60%  65%  70%  75%  80%  85%  90%  95%  
2020-06-24 15:03:56 | Completed download of qimg file: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:03:56 | Load qimg file onto Qumulo Cluster via API: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:04:12 | qimg loaded: /upgrade/qumulo_upgrade_3.1.2.qimg
2020-06-24 15:04:12 | delete local qimg: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:04:12 | Completed download of qimg(s) to Qumulo cluster
2020-06-24 15:04:12 | upgrade to: 3.1.0 with qimg: qumulo_upgrade_3.1.0.qimg
2020-06-24 15:04:12 | Preparing cluster for upgrade. Cluster will be fully available during this time.
2020-06-24 15:04:12 | Preparing...
2020-06-24 15:04:29 | Preparing...
2020-06-24 15:04:46 | Preparing...
2020-06-24 15:05:03 | Upgrade prepared for: /upgrade/qumulo_upgrade_3.1.0.qimg - status: UPGRADE_PREPARED
2020-06-24 15:05:03 | Begin upgrade arm process.
2020-06-24 15:05:34 | Qumulo cluster armed with /upgrade/qumulo_upgrade_3.1.0.qimg. Reloading Qumulo.
2020-06-24 15:05:44 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:06:04 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:06:24 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:06:44 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:07:04 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:07:24 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:07:44 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:08:04 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:08:24 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:08:44 | ... Loading new Qumulo Software version: /upgrade/qumulo_upgrade_3.1.0.qimg ...
2020-06-24 15:08:51 | Completed upgrade to 3.1.0
2020-06-24 15:08:51 | --------------------------------------------------------------------------------
2020-06-24 15:08:51 | upgrade to: 3.1.2 with qimg: qumulo_upgrade_3.1.2.qimg
2020-06-24 15:08:51 | Preparing cluster for upgrade. Cluster will be fully available during this time.
2020-06-24 15:08:51 | Preparing...
2020-06-24 15:09:08 | Preparing...
2020-06-24 15:09:25 | Preparing...
2020-06-24 15:09:42 | Preparing...
2020-06-24 15:09:59 | Upgrade prepared for: /upgrade/qumulo_upgrade_3.1.2.qimg - status: UPGRADE_PREPARED
2020-06-24 15:09:59 | Begin upgrade arm process.
Traceback (most recent call last):
  File "/data/qupgrade.py", line 398, in <module>
    upgrade_cluster()
  File "/data/qupgrade.py", line 394, in upgrade_cluster
    qr.upgrade_cluster(args.vers, api, sharepass=args.sharepass, download_only = args.download_only)
  File "/data/qupgrade.py", line 257, in upgrade_cluster
    self.install_upgrades(api)
  File "/data/qupgrade.py", line 184, in install_upgrades
    api.upgrade_to(d['release'], "%s/%s" % (UPGRADE_PATH, d['qimg']))
  File "/data/qupgrade.py", line 378, in upgrade_to
    self.upgrade_arm(qimg_path)
  File "/data/qupgrade.py", line 333, in upgrade_arm
    resp = self.rc.upgrade.config_put(qimg_path, 'UPGRADE_TARGET_ARM')
  File "/usr/local/lib/python2.7/site-packages/qumulo/rest_client.py", line 81, in wrapper
    self.client.conninfo, self.client.credentials, *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/qumulo/rest/upgrade.py", line 48, in config_put
    return request.rest_request(conninfo, credentials, method, str(uri), body=req)
  File "/usr/local/lib/python2.7/site-packages/qumulo/lib/request.py", line 596, in rest_request
    rest.get_response()
  File "/usr/local/lib/python2.7/site-packages/qumulo/lib/request.py", line 520, in get_response
    self.response = self.conn.getresponse()
  File "/usr/local/lib/python2.7/httplib.py", line 1161, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)
```

Thank you

**Comment by TommyUnger** [comment]
Unfortunately, this isn't an issue with the qupgrade.py script, it's an issue with calling ARM via our API. Please reach out to your Customer Success Manager via Slack or email to inform them of the bug. The specific bug is that this bit of our API code is taking too long: `rest_client.upgrade.config_put(qimg_path, 'UPGRADE_TARGET_ARM')` This call should return in milliseconds, not dozens of seconds or minutes.
