### ISSUE TITLE
multiprocessing error on walk

### ISSUE THREAD

**Issue by SLMitch** [Qumulo/power-tools#9]
Hi,

"sometime" (not always), i have this error when i launch the tree walk full to get  file (arround 300 000 files + folders )

Process PoolWorker-10:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/app/qtreewalk.py", line 73, in worker_main
    list_dir(rc, item, out_file)
  File "/app/qtreewalk.py", line 49, in list_dir
    next_page = r['paging']['next']
UnboundLocalError: local variable 'r' referenced before assignment
Traceback (most recent call last):
.....
  File "/app/qtreewalk.py", line 98, in walk_tree
    time.sleep(0.1)
KeyboardInterrupt

When it occur, the script don't stop and I had to kill it (CTL+C) (we see the KeyboardInterrupt)

I see the lot of  out-* file, but the script "hang" , after finishing (  wc -l out-*|grep total
  297217 total
) (which is the good result for the final file-list.txt file).

If I launch again, it can be OK without problem, or same error again.

**Comment by TommyUnger** [comment]
I'll take a look at this. I have a pretty good idea of the issue. In the meantime, please check out this much more robust approach to file system walks: https://github.com/TommyUnger/qumulo-filesystem-walk

**Comment by TommyUnger** [comment]
Added some better handling for pagination with the API.
